ALTER TABLE `reviews` ADD COLUMN `created` DATE NOT NULL DEFAULT '0000-00-00' AFTER `id`;
ALTER TABLE `reviews` ADD COLUMN `summary` TEXT(255) NOT NULL AFTER `effectiveness_rating`;
ALTER TABLE `reviews` ADD COLUMN `overall_rating` TINYINT(4) AS (CEILING((`ease_rating` + `effectiveness_rating`)/2)) VIRTUAL NOT NULL;
ALTER TABLE `reviews` MODIFY COLUMN `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `reviews` MODIFY COLUMN `uid` INT(11) UNSIGNED NOT NULL;
ALTER TABLE `reviews` MODIFY COLUMN `aid` INT(11) UNSIGNED NOT NULL;